[package]
name = "const_for"
version = "1.0.0"
edition = "2021"
authors = "Joachim Enggård Nebel"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]