[package]
name = "const_for"
version = "0.1.0"
edition = "2021"
authors = ["Joachim Enggård Nebel"]
description = "A macro for a simple for loop in const context"
readme = "README.md"
repository = "https://github.com/JENebel/const_for"
license = "MIT"
keywords = ["const", "for", "loop"]
categories = ["Development tools"]